### ISSUE TITLE
Preserving alt text

### ISSUE THREAD

**Issue by matteocontrini** [benallfree/mdsvex-enhanced-images#2]
Hi,

it seems that the alternative text specified in the markdown isn't currently passed over to the `<enhanced:img>` tag, so it's lost.

I'm using 0.2.0.

It shouldn't be too hard to pass that over, right?

**Comment by benallfree** [comment]
I was waiting for someone to mention that attributes aren’t forwarded. Yea that should be easy. I’ll take a look, or feel free to send a PR or paste a fix here.

**Comment by matteocontrini** [comment]
It wasn't working in 0.1.0 either, strangely, even if properties were forwarded. I'll take a closer look too, or, well, whoever does that first :)

Thanks!
