### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by lauriegriffiths** [benallfree/mdsvex-enhanced-images#4]
I tried this in a project and needed to install the dependency `unist-util-visit` .  Perhaps is is missing from this package?

After install the dependency manually everything worked as normal.

**Comment by benallfree** [comment]
Fixed in 0.2.3. 

I didn't think I needed it because mdsvex already has it as a dep. But depending on the package manager being used, it may not be in this package's search path so I went ahead and added it as a 1st class dep.

**Comment by benallfree** [comment]
Good to close?
